spring.application.name=projectmanager

spring.datasource.url=jdbc:postgresql://projectmanager.clums88ccm7z.ap-south-1.rds.amazonaws.com:5432/projectmanager
spring.datasource.username=postgres
spring.datasource.password=Postgres4321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info,metrics,beans,env,loggers
management.endpoint.health.show-details=always
